version: '2'
services:
  golang:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app:delegated
      # - '~/.gitconfig':'/root/.gitconfigß'
    entrypoint:
      - /bin/bash
